{% set name = "pyloudnorm" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyloudnorm-{{ version }}.tar.gz
  sha256: 8bf597658ea4e1975c275adf490f6deb5369ea409f2901f939915efa4b681b16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=58.0,<65
    - wheel
    - attrs
    - pip
  run:
    - python >={{ python_min }}
    - scipy >=1.0.1
    - numpy >=1.14.2
    - future >=0.16.0

test:
  imports:
    - pyloudnorm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/csteinmetz1/pyloudnorm
  summary: Implementation of ITU-R BS.1770-4 loudness algorithm in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
