schema_version: 1

context:
  name: pyloudnorm
  version: 0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyloudnorm-${{ version }}.tar.gz
  sha256: 8bf597658ea4e1975c275adf490f6deb5369ea409f2901f939915efa4b681b16

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - attrs
    - pip
  run:
    - python >=${{ python_min }}
    - scipy >=1.0.1
    - numpy >=1.14.2
    - future >=0.16.0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - pyloudnorm

about:
  summary: Implementation of ITU-R BS.1770-4 loudness algorithm in Python.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/csteinmetz1/pyloudnorm

extra:
  recipe-maintainers:
    - xhochy
